version: 2
run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  disable:
    - revive  # enable later when public docs stabilize
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sunflower-works/vision
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
