# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  tests:
    uses: sunflower-works/central-ci/.github/workflows/go-ci.yml@v1.1.0
    with:
      go-versions: '["1.24"]'
      os-matrix: '["ubuntu-latest"]'
      min-coverage: '60.0'
      race: 'true'
      tidy-check: 'true'
      coverage: 'true'
