# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Delegator: central-ci go-lint workflow
name: Lint
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  lint:
    uses: sunflower-works/central-ci/.github/workflows/go-lint.yml@v1
    with:
      go-version: '1.24'
      golangci-version: 'latest'
      run-staticcheck: 'false'
