# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Security
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  security:
    uses: sunflower-works/central-ci/.github/workflows/security.yml@v1
    with:
      go-version: '1.24'
      schedule-only: 'false'
