# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Security
"on":
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 1'
permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
