# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Delegator: central-ci yaml-lint workflow
name: YAML Lint
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  yaml-lint:
    uses: sunflower-works/central-ci/.github/workflows/yaml-lint.yml@v1
    with:
      actionlint-version: 'latest'
      yamllint: 'true'
      yamllint-config: '.yamllint.yml'
